"""
SLURM job-array grid evaluation for DeltaSigma emulator training.

Three-phase workflow (no MPI required):

Phase 1 — generate the parameter grid (once)::

    python run_emulator_grid.py \\
        --generate_grid_only \\
        --fit_case STANDARD_NFW \\
        --n_samples 100000 \\
        --output_dir emulator_grid/

Phase 2 — evaluate grid slices in parallel (SLURM job array)::

    # Each array job reads its slice from disk and writes grid_rank{i}.npz
    SLURM_ARRAY_TASK_ID=0 SLURM_ARRAY_TASK_COUNT=5 \\
        python run_emulator_grid.py \\
        --job_array --n_jobs 5 \\
        --grid_path emulator_grid/param_grid_full.parquet \\
        --fit_case STANDARD_NFW \\
        --cache_path halo_center_lensing_cache.h5 \\
        --output_dir emulator_grid/

Phase 3 — merge per-job chunks::

    python run_emulator_grid.py \\
        --merge_only --n_jobs 5 \\
        --output_dir emulator_grid/

Single-process smoke test (no SLURM)::

    python run_emulator_grid.py --n_samples 50 --no_mpi

Job-array dry-run (two jobs locally)::

    SLURM_ARRAY_TASK_ID=0 SLURM_ARRAY_TASK_COUNT=2 \\
        python run_emulator_grid.py --job_array --n_jobs 2 \\
        --grid_path emulator_grid/param_grid_full.parquet --n_samples 50

See run_emulator_grid.slurm for the complete SLURM submission script that
handles job dependencies between the three phases automatically.

Notes
-----
* Each job imports JAX independently — no deadlock risk.
* Each job writes its own checkpoint file; if interrupted, resume by
  re-running the same command (run_hod_grid detects existing checkpoints).
* After all jobs finish and merge, train the emulator with::

      python -c "
      import numpy as np
      from HOD_NRV.utilsf.emulator_nn import train_emulator
      d = np.load('emulator_grid/grid_merged.npz', allow_pickle=True)
      train_emulator(d['params_array'], d['dsigma_array'], d['rp_centers'],
                     save_path='emulator_STANDARD_NFW.pt')
      "
"""

import argparse
import os
import numpy as np

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

def parse_args():
    parser = argparse.ArgumentParser(
        description="SLURM job-array DeltaSigma grid evaluation for emulator training"
    )
    parser.add_argument(
        "--fit_case",
        choices=["STANDARD_NFW", "EXTENDED_PROFILE", "CONFORMITY"],
        default="STANDARD_NFW",
        help="HOD model complexity (determines free parameters)",
    )
    parser.add_argument(
        "--n_samples",
        type=int,
        default=100_000,
        help="Total number of LHS grid points (split across all jobs)",
    )
    parser.add_argument(
        "--n_realizations",
        type=int,
        default=5,
        help="HOD realizations per grid point",
    )
    parser.add_argument(
        "--galaxy_fraction",
        type=float,
        default=0.10,
        help="Galaxy downsampling fraction per realization",
    )
    parser.add_argument(
        "--particle_fraction",
        type=float,
        default=0.05,
        help="Particle downsampling fraction (applied once at HaloOccupation init). "
             "Default 0.05 matches the optimal setting from benchmark_dsigma_convergence.py",
    )
    parser.add_argument(
        "--particle_seed",
        type=int,
        default=42,
        help="Random seed for particle subsampling",
    )
    parser.add_argument(
        "--cache_path",
        type=str,
        default=None,
        help="Path to a precomputed HaloCenterLensingCache HDF5 file "
             "(generated by precompute_halo_center_cache.py). "
             "Strongly recommended: enables method='optimized', giving 3-9x speedup "
             "over standard pycorr pair counting. If omitted, falls back to method='standard'.",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="emulator_grid",
        help="Directory for per-job checkpoint files and merged output",
    )
    parser.add_argument(
        "--checkpoint_every",
        type=int,
        default=200,
        help="Save checkpoint every N completed grid points",
    )
    parser.add_argument(
        "--base_seed",
        type=int,
        default=42,
        help="Base random seed for LHS + HOD realizations",
    )
    parser.add_argument(
        "--no_mpi",
        action="store_true",
        help="Run without MPI (single process, for local testing)",
    )
    # --- Job array arguments ---
    parser.add_argument(
        "--job_array",
        action="store_true",
        help="Activate job array mode: reads rank/size from SLURM_ARRAY_TASK_ID / "
             "SLURM_ARRAY_TASK_COUNT and loads the parameter grid from --grid_path",
    )
    parser.add_argument(
        "--n_jobs",
        type=int,
        default=1,
        help="Number of array jobs (fallback if SLURM_ARRAY_TASK_COUNT is not set)",
    )
    parser.add_argument(
        "--grid_path",
        type=str,
        default=None,
        help="Path to pre-saved param_grid_full.parquet (required with --job_array)",
    )
    parser.add_argument(
        "--generate_grid_only",
        action="store_true",
        help="Phase 1: generate and save the LHS parameter grid, then exit",
    )
    parser.add_argument(
        "--merge_only",
        action="store_true",
        help="Phase 3: merge per-job grid_rank{i}.npz chunks, then exit",
    )
    parser.add_argument(
        "--population_backend",
        choices=["jax", "numba"],
        default="numba",
        help="Galaxy population backend: 'numba' (default, faster, float64) or 'jax'",
    )
    parser.add_argument(
        "--subhalo_path",
        type=str,
        default=None,
        help="Path to subhalo_catalogue.npz (from precompute_subhalo_catalogue.py). "
             "When provided, satellites are sampled from real N-body subhalos instead "
             "of NFW profiles. Requires the halo_path parquet to be the matching "
             "host_catalogue.parquet from the same preprocessing run.",
    )
    parser.add_argument(
        "--elg_satellite",
        type=lambda x: bool(int(x)),
        default=0,
        metavar="{0,1}",
        help="Use ELG satellite cutoff (1) or standard kappa (0)",
    )
    return parser.parse_args()


# ---------------------------------------------------------------------------
# Flamingo data paths and cosmology (edit for your cluster)
# ---------------------------------------------------------------------------

HALO_PATH = "/Users/ler13nrv/Documents/flamingo_data/parquet_halo_catalogue_L1000N1800.parquet"
PARTICLE_PATH = "/Users/ler13nrv/Documents/flamingo_data/particle_catalogue_L1000N1800_downsampled.parquet"

LBOX = 681.0          # Mpc/h
ZEFF = 1.0
MASS_DEFINITION = "MassDef200m"
TARGET_NGAL = 2e-4    # (Mpc/h)^-3
M1_FIXED = 13.0       # log10 M_sun/h

COLUMN_MAPPING = {
    "x": "x", "y": "y", "z": "z",
    "vx": "vx", "vy": "vy", "vz": "vz",
    "mass": "mass", "radius": "rvir", "c": "c", "vrms": "vrms",
}

COSMO_PARAMS = {
    "h": 0.681,
    "Omc": 0.306 - 0.0486 - 1.39e-3,
    "Omb": 0.0486,
    "A_s": 2.099e-9,
    "n_s": 0.967,
    "Omnu": 1.39e-3,
}

RP_BINS = np.geomspace(0.1, 50.0, 16)  # 15 bins

# ---------------------------------------------------------------------------
# Parameter ranges per fit case
# ---------------------------------------------------------------------------

_BASE_RANGES = {
    "As":         (0.002, 0.05),
    "Mmin":       (11.5, 13.5),
    "sig_M":      (0.1, 2.0),
    "gamma":      (0.0, 10.0),
    "alpha":      (0.1, 2.0),
    "kappa":      (0.1, 2.0),
    "lambda_NFW": (0.1, 2.0),
}

_EXTENDED_RANGES = {
    "f_exp": (0.1, 0.9),
    "tau":   (1.0, 10.0),
}

_CONFORMITY_RANGES = {
    "kappa_EE": (0.5, 2.0),
}

_ELG_SATELLITE_RANGES = {
    "Mcut": (11.0, 13.0),
    "Mmax": (13.5, 15.5),
}

FIXED_PARAMS = {"M1": M1_FIXED}


def get_param_ranges(fit_case_str: str, elg_satellite: bool = False) -> dict:
    if elg_satellite:
        base = {k: v for k, v in _BASE_RANGES.items() if k != "kappa"}
        base.update(_ELG_SATELLITE_RANGES)
    else:
        base = dict(_BASE_RANGES)
    if fit_case_str in ("EXTENDED_PROFILE", "CONFORMITY"):
        base.update(_EXTENDED_RANGES)
    if fit_case_str == "CONFORMITY":
        base.update(_CONFORMITY_RANGES)
    return base


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    args = parse_args()

    import pandas as pd
    from HOD_NRV.HOD_numerical.HOD import HaloOccupation
    from HOD_NRV.HOD_numerical.twopoint_calculator.halo_center_lensing import HaloCenterLensingCache
    from HOD_NRV.utilsf.emulator_utils import (
        generate_hod_parameter_grid,
        run_hod_grid,
        merge_grid_chunks,
    )

    os.makedirs(args.output_dir, exist_ok=True)

    # -----------------------------------------------------------------------
    # Phase 1: generate grid and exit
    # -----------------------------------------------------------------------
    if args.generate_grid_only:
        print(f"[Phase 1] Loading halo catalog from {HALO_PATH}")
        halo_gen = HaloOccupation(
            cosmology=COSMO_PARAMS,
            zeff=ZEFF,
            Lbox=LBOX,
            column_mapping=COLUMN_MAPPING,
            mass_definition=MASS_DEFINITION,
            halo_path=HALO_PATH,
            DataFrame_part=None,   # particles not needed for grid generation
            apply_rsd=False,
            do_test=False,
            population_backend=args.population_backend,
            subhalo_path=args.subhalo_path,
        )
        hod_type = "ELG_mHMQ"
        use_conformity = (args.fit_case == "CONFORMITY")
        use_elg_satellite = args.elg_satellite
        halo_gen.set_halo_model(hod_type, conformity=use_conformity, elg_satellite=use_elg_satellite)

        param_ranges = get_param_ranges(args.fit_case, elg_satellite=use_elg_satellite)
        include_nfw_extensions = (args.fit_case in ("EXTENDED_PROFILE", "CONFORMITY"))
        print(f"[Phase 1] Generating {args.n_samples} LHS grid points "
              f"for fit_case={args.fit_case}")
        param_grid = generate_hod_parameter_grid(
            halo=halo_gen,
            hod_type=hod_type,
            param_ranges=param_ranges,
            n_samples=args.n_samples,
            target_ngal=TARGET_NGAL,
            fixed_params=FIXED_PARAMS,
            random_seed=args.base_seed,
            conformity=use_conformity,
            elg_satellite=use_elg_satellite,
            include_nfw_extensions=include_nfw_extensions,
            verbose=True,
        )
        grid_meta_path = os.path.join(args.output_dir, "param_grid_full.parquet")
        param_grid.to_parquet(grid_meta_path, index=False)
        print(f"[Phase 1] Full parameter grid saved to {grid_meta_path} "
              f"({len(param_grid)} rows)")
        print(f"[Phase 1] Done. Submit Phase 2 (job array) next.")
        return

    # -----------------------------------------------------------------------
    # Phase 3: merge chunks and exit
    # -----------------------------------------------------------------------
    if args.merge_only:
        merged_path = os.path.join(args.output_dir, "grid_merged.npz")
        print(f"[Phase 3] Merging {args.n_jobs} per-job chunks in {args.output_dir}...")
        params_merged, rp_centers, dsigma_merged = merge_grid_chunks(
            directory=args.output_dir,
            n_ranks=args.n_jobs,
            output=merged_path,
        )
        print(f"[Phase 3] Merged grid: {params_merged.shape[0]} points, "
              f"{dsigma_merged.shape[1]} rp bins")
        print(f"[Phase 3] Merged file: {merged_path}")
        print()
        print("Next step — train the emulator:")
        fit_case = args.fit_case
        print(f"  python -c \"")
        print(f"  import numpy as np")
        print(f"  from HOD_NRV.utilsf.emulator_nn import train_emulator")
        print(f"  d = np.load('{merged_path}', allow_pickle=True)")
        print(f"  train_emulator(d['params_array'], d['dsigma_array'], d['rp_centers'],")
        print(f"                 save_path='emulator_{fit_case}.pt')\"")
        return

    # -----------------------------------------------------------------------
    # Phase 2: evaluate grid slice
    # -----------------------------------------------------------------------

    # Determine rank / size
    if args.no_mpi:
        rank, size = 0, 1
    elif args.job_array:
        rank = int(os.environ.get("SLURM_ARRAY_TASK_ID", 0))
        size = int(os.environ.get("SLURM_ARRAY_TASK_COUNT", args.n_jobs))
    else:
        rank, size = 0, 1   # bare invocation = single process

    # Load or generate parameter grid
    if args.job_array:
        if args.grid_path is None:
            raise ValueError("--grid_path is required when using --job_array")
        print(f"[job {rank}/{size}] Loading parameter grid from {args.grid_path}")
        param_grid = pd.read_parquet(args.grid_path)
    else:
        # Single-process path: generate in-process and save for reference
        print(f"[rank {rank}] Loading halo catalog from {HALO_PATH}")
        halo_grid = HaloOccupation(
            cosmology=COSMO_PARAMS,
            zeff=ZEFF,
            Lbox=LBOX,
            column_mapping=COLUMN_MAPPING,
            mass_definition=MASS_DEFINITION,
            halo_path=HALO_PATH,
            DataFrame_part=None,
            apply_rsd=False,
            do_test=False,
            population_backend=args.population_backend,
            subhalo_path=args.subhalo_path,
        )
        hod_type_tmp = "ELG_mHMQ"
        use_conformity_tmp = (args.fit_case == "CONFORMITY")
        use_elg_satellite_tmp = args.elg_satellite
        halo_grid.set_halo_model(hod_type_tmp, conformity=use_conformity_tmp, elg_satellite=use_elg_satellite_tmp)

        param_ranges = get_param_ranges(args.fit_case, elg_satellite=use_elg_satellite_tmp)
        include_nfw_extensions_tmp = (args.fit_case in ("EXTENDED_PROFILE", "CONFORMITY"))
        print(f"[rank {rank}] Generating {args.n_samples} LHS grid points "
              f"for fit_case={args.fit_case}")
        param_grid = generate_hod_parameter_grid(
            halo=halo_grid,
            hod_type=hod_type_tmp,
            param_ranges=param_ranges,
            n_samples=args.n_samples,
            target_ngal=TARGET_NGAL,
            fixed_params=FIXED_PARAMS,
            random_seed=args.base_seed,
            conformity=use_conformity_tmp,
            elg_satellite=use_elg_satellite_tmp,
            include_nfw_extensions=include_nfw_extensions_tmp,
            verbose=True,
        )
        grid_meta_path = os.path.join(args.output_dir, "param_grid_full.parquet")
        param_grid.to_parquet(grid_meta_path, index=False)
        print(f"[rank {rank}] Full parameter grid saved to {grid_meta_path}")

    # Slice grid for this job
    n_total = len(param_grid)
    chunk = n_total // size
    start = rank * chunk
    end = start + chunk if rank < size - 1 else n_total
    my_grid = param_grid.iloc[start:end].reset_index(drop=True)

    print(f"[job {rank}/{size}] Processing rows {start}:{end} ({len(my_grid)} points)")

    # Load halo + particle catalogs
    print(f"[job {rank}/{size}] Loading halo catalog...")
    halo = HaloOccupation(
        cosmology=COSMO_PARAMS,
        zeff=ZEFF,
        Lbox=LBOX,
        column_mapping=COLUMN_MAPPING,
        mass_definition=MASS_DEFINITION,
        halo_path=HALO_PATH,
        DataFrame_part=pd.read_parquet(PARTICLE_PATH),
        apply_rsd=True,
        do_test=False,
        particle_fraction=args.particle_fraction,
        particle_subsample_seed=args.particle_seed,
        population_backend=args.population_backend,
        subhalo_path=args.subhalo_path,
    )
    if args.subhalo_path is not None:
        print(f"[job {rank}/{size}] Subhalo satellite mode: {args.subhalo_path}")
    print(f"[job {rank}/{size}] Population backend: {args.population_backend}")
    print(f"[job {rank}/{size}] Particle fraction: {args.particle_fraction} "
          f"(seed={args.particle_seed})")
    hod_type = "ELG_mHMQ"
    use_conformity = (args.fit_case == "CONFORMITY")
    use_elg_satellite = args.elg_satellite
    halo.set_halo_model(hod_type, conformity=use_conformity, elg_satellite=use_elg_satellite)
    print(f"[job {rank}/{size}] Catalog loaded.")

    # Load precomputed halo-center lensing cache
    precomputed_cache = None
    if args.cache_path is not None:
        if not os.path.exists(args.cache_path):
            raise FileNotFoundError(
                f"[job {rank}/{size}] Cache file not found: {args.cache_path}\n"
                f"Run common_test/precompute_halo_center_cache.py first."
            )
        print(f"[job {rank}/{size}] Loading halo-center lensing cache from {args.cache_path}...")
        precomputed_cache = HaloCenterLensingCache.load(args.cache_path)
        print(f"[job {rank}/{size}] Cache loaded ({len(precomputed_cache.deltasigma)} halos).")
    else:
        print(f"[job {rank}/{size}] No cache provided — using method='standard' (slower). "
              f"Consider running precompute_halo_center_cache.py and passing --cache_path.")

    # Evaluate grid
    save_path = os.path.join(args.output_dir, f"grid_rank{rank}.npz")
    _, rp_centers, _ = run_hod_grid(
        my_grid,
        halo,
        RP_BINS,
        n_realizations=args.n_realizations,
        galaxy_fraction=args.galaxy_fraction,
        precomputed_cache=precomputed_cache,
        save_path=save_path,
        checkpoint_every=args.checkpoint_every,
        base_seed=args.base_seed + start,   # offset seed by job's start index
        mpi_rank=rank,
        target_ngal=TARGET_NGAL,
    )

    print(f"[job {rank}/{size}] Done. Results saved to {save_path}")
    if not args.job_array:
        # Single-process: merge immediately
        merged_path = os.path.join(args.output_dir, "grid_merged.npz")
        print("[rank 0] Merging per-rank chunks...")
        params_merged, rp_centers, dsigma_merged = merge_grid_chunks(
            directory=args.output_dir,
            n_ranks=size,
            output=merged_path,
        )
        print(f"[rank 0] Merged grid: {params_merged.shape[0]} points, "
              f"{dsigma_merged.shape[1]} rp bins")
        print(f"[rank 0] Merged file: {merged_path}")
        print()
        print("Next step — train the emulator:")
        print(f"  python -c \"")
        print(f"  import numpy as np")
        print(f"  from HOD_NRV.utilsf.emulator_nn import train_emulator")
        print(f"  d = np.load('{merged_path}', allow_pickle=True)")
        print(f"  train_emulator(d['params_array'], d['dsigma_array'], d['rp_centers'],")
        print(f"                 save_path='emulator_{args.fit_case}.pt')\"")
    else:
        print(f"[job {rank}/{size}] Run Phase 3 (--merge_only) after all jobs complete.")


if __name__ == "__main__":
    main()
